//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetInvoiceOption
    {
        public int Id { get; set; }
        public string PaymentTerms { get; set; }
        public string Title { get; set; }
        public string Siret { get; set; }
        public string APE { get; set; }
        public string VatNo { get; set; }
        public string PaymentInstructiones { get; set; }
        public Nullable<int> NextNumber { get; set; }
        public Nullable<bool> HideName { get; set; }
        public Nullable<bool> HidePaymentHistory { get; set; }
        public string PrintFormate { get; set; }
    }
}
