//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBookingForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBookingForm()
        {
            this.AspNetBookingOptiones = new HashSet<AspNetBookingOptione>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Name { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> Mobile { get; set; }
        public Nullable<bool> Adress1 { get; set; }
        public Nullable<bool> Adress2 { get; set; }
        public Nullable<bool> Note { get; set; }
        public Nullable<bool> City { get; set; }
        public Nullable<bool> ZipCode { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Country { get; set; }
        public Nullable<bool> Captcha { get; set; }
        public Nullable<bool> Terms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBookingOptione> AspNetBookingOptiones { get; set; }
    }
}
