//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetWorkingWeekTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetWorkingWeekTime()
        {
            this.AspNetCustomers = new HashSet<AspNetCustomer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MondayID { get; set; }
        public Nullable<int> TuesdayID { get; set; }
        public Nullable<int> WednesdayID { get; set; }
        public Nullable<int> ThursdayID { get; set; }
        public Nullable<int> FridayID { get; set; }
        public Nullable<int> SaturdayID { get; set; }
        public Nullable<int> SundayID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCustomer> AspNetCustomers { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime1 { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime2 { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime3 { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime4 { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime5 { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime6 { get; set; }
    }
}
