//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCompanyNotifination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetCompanyNotifination()
        {
            this.AspNetCompanyCustomers = new HashSet<AspNetCompanyCustomer>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> SendAppointmentMessage { get; set; }
        public Nullable<bool> DefaultEmailRemainder { get; set; }
        public Nullable<bool> DifferentEmailInterval { get; set; }
        public string EmailBeforeArrive { get; set; }
        public Nullable<bool> DefaultSmsRemainder { get; set; }
        public Nullable<bool> DifferentSmsInterval { get; set; }
        public string SmsBeforeArrive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCompanyCustomer> AspNetCompanyCustomers { get; set; }
    }
}
