//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBookingOptione
    {
        public int Id { get; set; }
        public string SetMins { get; set; }
        public string BeforeTime { get; set; }
        public string StartTime { get; set; }
        public string DayType { get; set; }
        public Nullable<int> CancelationId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> EmailNotifyId { get; set; }
        public Nullable<int> TermsId { get; set; }
        public Nullable<int> RemainderId { get; set; }
    
        public virtual AspNetBookingCancelation AspNetBookingCancelation { get; set; }
        public virtual AspNetBookingForm AspNetBookingForm { get; set; }
        public virtual AspNetEmailNotification AspNetEmailNotification { get; set; }
        public virtual AspNetBookingPayment AspNetBookingPayment { get; set; }
        public virtual AspNetRemainder AspNetRemainder { get; set; }
        public virtual AspNetBookingTerm AspNetBookingTerm { get; set; }
    }
}
