//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBooking()
        {
            this.AspNetBookingServices = new HashSet<AspNetBookingService>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UniqueId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Status { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<double> PriceW_OVat { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> VoucherTotal { get; set; }
        public string Notes { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> BookingItemId { get; set; }
    
        public virtual AspNetBookingItem AspNetBookingItem { get; set; }
        public virtual AspNetGiftVoucher AspNetGiftVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBookingService> AspNetBookingServices { get; set; }
    }
}
