//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRemainder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRemainder()
        {
            this.AspNetBookingOptiones = new HashSet<AspNetBookingOptione>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> SendRemainder { get; set; }
        public Nullable<int> SendEmailHours { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> SmsSendingHours { get; set; }
        public string SmsMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBookingOptione> AspNetBookingOptiones { get; set; }
    }
}
