//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetWorkingTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetWorkingTime()
        {
            this.AspNetWorkingWeekTimes = new HashSet<AspNetWorkingWeekTime>();
            this.AspNetWorkingWeekTimes1 = new HashSet<AspNetWorkingWeekTime>();
            this.AspNetWorkingWeekTimes2 = new HashSet<AspNetWorkingWeekTime>();
            this.AspNetWorkingWeekTimes3 = new HashSet<AspNetWorkingWeekTime>();
            this.AspNetWorkingWeekTimes4 = new HashSet<AspNetWorkingWeekTime>();
            this.AspNetWorkingWeekTimes5 = new HashSet<AspNetWorkingWeekTime>();
            this.AspNetWorkingWeekTimes6 = new HashSet<AspNetWorkingWeekTime>();
        }
    
        public int Id { get; set; }
        public string Day { get; set; }
        public Nullable<bool> isoff { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> LunchFrom { get; set; }
        public Nullable<System.DateTime> LunchToo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetWorkingWeekTime> AspNetWorkingWeekTimes6 { get; set; }
    }
}
