//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBookingCancelation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBookingCancelation()
        {
            this.AspNetBookingOptiones = new HashSet<AspNetBookingOptione>();
        }
    
        public int Id { get; set; }
        public string CancleLink { get; set; }
        public Nullable<bool> Upto { get; set; }
        public string UptoTime { get; set; }
        public Nullable<bool> Never { get; set; }
        public Nullable<bool> Anytime { get; set; }
        public string Terms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBookingOptione> AspNetBookingOptiones { get; set; }
    }
}
