//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBookingPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBookingPayment()
        {
            this.AspNetBookingOptiones = new HashSet<AspNetBookingOptione>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> DisablePayment { get; set; }
        public string DepositAmmount { get; set; }
        public string AmmountType { get; set; }
        public Nullable<bool> AllowPaypal { get; set; }
        public string PaypalAdress { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<bool> CreditCardDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBookingOptione> AspNetBookingOptiones { get; set; }
    }
}
