//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCustomerLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetCustomerLocation()
        {
            this.AspNetAgencies = new HashSet<AspNetAgency>();
            this.AspNetCustomers = new HashSet<AspNetCustomer>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IntervensionZone { get; set; }
        public Nullable<double> Radius { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAgency> AspNetAgencies { get; set; }
        public virtual AspNetCountry AspNetCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCustomer> AspNetCustomers { get; set; }
    }
}
