//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmployee
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SMSNumber { get; set; }
        public Nullable<bool> SendBookingSMS { get; set; }
        public Nullable<bool> SendBookingMail { get; set; }
        public string WorkingPlace { get; set; }
        public Nullable<int> WorkingId { get; set; }
        public Nullable<bool> CelenderSync { get; set; }
        public string Status { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string Photo { get; set; }
        public Nullable<int> ServiceGroupId { get; set; }
        public Nullable<int> EmployeeServiceId { get; set; }
    
        public virtual AspNetAgency AspNetAgency { get; set; }
        public virtual AspNetEmployee_Services AspNetEmployee_Services { get; set; }
        public virtual AspNetServiceGroup AspNetServiceGroup { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetWorkingWeekTime AspNetWorkingWeekTime { get; set; }
    }
}
