//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetService_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetService_Group()
        {
            this.AspNetComanyServices = new HashSet<AspNetComanyService>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetComanyService> AspNetComanyServices { get; set; }
        public virtual AspNetService AspNetService { get; set; }
        public virtual AspNetServiceGroup AspNetServiceGroup { get; set; }
    }
}
