//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmployee
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SMSNumber { get; set; }
        public Nullable<bool> BookingSMS { get; set; }
        public Nullable<bool> BookingMail { get; set; }
        public Nullable<bool> ThaiMessage { get; set; }
        public Nullable<bool> CalliforniaMessage { get; set; }
        public string WorkingPlace { get; set; }
        public Nullable<bool> AgencyCheck1 { get; set; }
        public Nullable<bool> AgencyCheck2 { get; set; }
        public Nullable<int> WorkingId { get; set; }
        public Nullable<bool> CelenderSync { get; set; }
        public string Status { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AgencyId { get; set; }
    
        public virtual AspNetAgency AspNetAgency { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetWorkingTime AspNetWorkingTime { get; set; }
    }
}
