//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shad_BookingApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingModelEntities : DbContext
    {
        public BookingModelEntities()
            : base("name=BookingModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetAgency> AspNetAgencies { get; set; }
        public virtual DbSet<AspNetBooking> AspNetBookings { get; set; }
        public virtual DbSet<AspNetBookingCancelation> AspNetBookingCancelations { get; set; }
        public virtual DbSet<AspNetBookingForm> AspNetBookingForms { get; set; }
        public virtual DbSet<AspNetBookingItem> AspNetBookingItems { get; set; }
        public virtual DbSet<AspNetBookingOptione> AspNetBookingOptiones { get; set; }
        public virtual DbSet<AspNetBookingPayment> AspNetBookingPayments { get; set; }
        public virtual DbSet<AspNetBookingPaymentType> AspNetBookingPaymentTypes { get; set; }
        public virtual DbSet<AspNetBookingService> AspNetBookingServices { get; set; }
        public virtual DbSet<AspNetBookingTerm> AspNetBookingTerms { get; set; }
        public virtual DbSet<AspNetBusinessCatageory> AspNetBusinessCatageories { get; set; }
        public virtual DbSet<AspNetBusinessSubCatageory> AspNetBusinessSubCatageories { get; set; }
        public virtual DbSet<AspNetCompanyCustomer> AspNetCompanyCustomers { get; set; }
        public virtual DbSet<AspNetCompanyNotifination> AspNetCompanyNotifinations { get; set; }
        public virtual DbSet<AspNetCustomer_SubCatageory> AspNetCustomer_SubCatageory { get; set; }
        public virtual DbSet<AspNetCustomerBusinessDetail> AspNetCustomerBusinessDetails { get; set; }
        public virtual DbSet<AspNetCustomerContact> AspNetCustomerContacts { get; set; }
        public virtual DbSet<AspNetCustomerDetail> AspNetCustomerDetails { get; set; }
        public virtual DbSet<AspNetCustomerGallery> AspNetCustomerGalleries { get; set; }
        public virtual DbSet<AspNetCustomerLocation> AspNetCustomerLocations { get; set; }
        public virtual DbSet<AspNetCustomerRegion> AspNetCustomerRegions { get; set; }
        public virtual DbSet<AspNetCustomer> AspNetCustomers { get; set; }
        public virtual DbSet<AspNetCustomerSM> AspNetCustomerSMS { get; set; }
        public virtual DbSet<AspNetCustomerType> AspNetCustomerTypes { get; set; }
        public virtual DbSet<AspNetDiscount> AspNetDiscounts { get; set; }
        public virtual DbSet<AspNetEmailNotification> AspNetEmailNotifications { get; set; }
        public virtual DbSet<AspNetEmailNotificationType> AspNetEmailNotificationTypes { get; set; }
        public virtual DbSet<AspNetEmployee> AspNetEmployees { get; set; }
        public virtual DbSet<AspNetExpire> AspNetExpires { get; set; }
        public virtual DbSet<AspNetGiftVoucher> AspNetGiftVouchers { get; set; }
        public virtual DbSet<AspNetInvoice> AspNetInvoices { get; set; }
        public virtual DbSet<AspNetInvoiceOption> AspNetInvoiceOptions { get; set; }
        public virtual DbSet<AspNetItem> AspNetItems { get; set; }
        public virtual DbSet<AspNetRemainder> AspNetRemainders { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetService> AspNetServices { get; set; }
        public virtual DbSet<AspNetService_Group> AspNetService_Group { get; set; }
        public virtual DbSet<AspNetServiceGroup> AspNetServiceGroups { get; set; }
        public virtual DbSet<AspNetSocial> AspNetSocials { get; set; }
        public virtual DbSet<AspNetTax> AspNetTaxes { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetWorkingTime> AspNetWorkingTimes { get; set; }
        public virtual DbSet<AspNetWorkingWeekTime> AspNetWorkingWeekTimes { get; set; }
    }
}
